version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
  # db:
  #   image: postgres
  #   ports: 
  #       - 5432:5432
  #   environment: 
  #       - POSTGRES_USER=postgres
  #       - POSTGRES_PASSWORD=geoserver
  #       - POSTGRES_DB=geoserver
  # redis:
  #   image: redis:alpine

  # build:
  #   network: host
